### ISSUE TITLE
test

### ISSUE THREAD

**Issue by AbdelrahmanElsaid** [BeamNG/beamng-ros-integration#1]

**Comment by AbdelrahmanElsaid** [comment]
i found that this erro was because of wrong setup on WSL2 side and ROS side, i re-setup everything, and this issue isn't there anymore

**Comment by RoboticistAbdulrahman** [comment]
i found the solution by changing the scenarios permission to be 777
cd ~/catkin_ws/src/beamng-ros-integration/beamng_control/test/scenarios
sudo chmod 777 *

another solution can be 
sudo rosdep fix-permissions && rosdep update
