### ISSUE TITLE
can't find example.launch file in beamng_control

### ISSUE THREAD

**Issue by Pradur241** [BeamNG/beamng-ros-integration#32]
I have downloaded this package and catkin_make it in wsl2. But I can't find example.launch in beamng_control. Instead,  I tried to launch control.launch. And I got this error Message:

![image](https://github.com/BeamNG/beamng-ros-integration/assets/57956342/fb8e67c7-937c-4530-b412-989f81800733)

**Comment by Pradur241** [comment]
Thank you for your hard work and your Solutions! It's worked!

![image](https://github.com/BeamNG/beamng-ros-integration/assets/57956342/df223ae3-32a7-4692-9329-cd789c50599e)

**Comment by AbdelrahmanElsaidElsawy** [comment]
I'm really glad to hear that everything worked out for you! If you need any more help or have any other questions, feel free to ask. Good luck with everything you're working on!
